### ISSUE TITLE
What would it be good for?

### ISSUE THREAD

**Issue by WAUthethird** [MaterialMusic/materialmusic.github.io#1]
Hey - just wanted to say that I think this is a very interesting project with a lot of potential - [love the UI!] but I wanted to know what exactly it would be used for -- is there a use? Or is it simply for listening to music? If it's going to be a big platform, it's not so good to have just one row of playlists on the site -- you'll need to have multiple. This _could_ potentially be a massive platform with millions of users; it just depends on what you'd use it for.

**Comment by pigcake999** [comment]
I'm going to hook it up to the Spotify API. It will be a music platform with DJ and karaoke possibility. But for now just this prototype. If you want you can help?

**Comment by WAUthethird** [comment]
That'd be cool!
